version: "3.8"
services:
  db:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "15432:5432"
    volumes:
      - newsroom-db:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - newsroom-network
  app:
    build: .
    image: newsroom_app:latest
    depends_on:
      - db
    env_file:
      - .env
    environment:
      # Fall back to compose-provided db host/port if not in .env
      DB_HOST: ${DB_HOST:-db}
      DB_PORT: ${DB_PORT:-5432}
    volumes:
      - ./newsfeeds.yaml:/app/newsfeeds.yaml:ro
      - ./static/images:/app/static/images
      - hf-cache:/root/.cache/huggingface
    restart: unless-stopped
    command: ["python", "main.py"]
    networks:
      - newsroom-network
  email_processor:
    image: newsroom_app:latest
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DB_HOST: ${DB_HOST:-db}
      DB_PORT: ${DB_PORT:-5432}
    volumes:
      - hf-cache:/root/.cache/huggingface
    restart: unless-stopped
    command: ["/bin/sh", "-c", "while true; do python email_processor.py; sleep 300; done"]
    networks:
      - newsroom-network

networks:
  newsroom-network:
    external: true

volumes:
  newsroom-db:
  hf-cache: