version: "3.8"
services:
  db:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "15432:5432"
    volumes:
      - newsroom-db:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
volumes:
  newsroom-db:
